[workspace]

[package]
name = "braillify-desktop"
version = "0.1.0"
description = "Braillify Windows desktop application"
authors = ["devfive"]
edition = "2024"
rust-version = "1.95"

[lib]
name = "braillify_desktop_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
braillify = { path = "../../../libs/braillify", default-features = false }
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-window-state = "2"

[dev-dependencies]
rstest = "0.26"
